const fs = require('fs');
const path = require('path');

const envPath = path.join(__dirname, '.env');
const outPath = path.join(__dirname, 'env.js');

try {
  if (!fs.existsSync(envPath)) {
    console.error('No .env file found. Please create one.');
    process.exit(1);
  }

  const content = fs.readFileSync(envPath, 'utf8');
  const envObj = {};

  content.split('\n').forEach(line => {
    line = line.trim();
    if (line && !line.startsWith('#') && line.includes('=')) {
      const [key, ...val] = line.split('=');
      envObj[key.trim()] = val.join('=').trim().replace(/(^"|"$)/g, ''); // remove wrapping quotes if exist
    }
  });

  const jsContent = `// Auto-generated by build_env.js. Do not commit this file.\nconst ENV = ${JSON.stringify(envObj, null, 2)};\n`;
  fs.writeFileSync(outPath, jsContent);
  console.log('Successfully generated env.js from .env');
} catch (error) {
  console.error('Error generating env.js:', error);
}
